apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: ns-hiorder
  labels:
    app: store
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: store
