apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: ns-hiorder
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: member