apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-web-ingress
  namespace: ns-hiorder
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /hi
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
